### ISSUE TITLE
needs to specify license

### ISSUE THREAD

**Issue by hyperknot** [haysclark/adlmflexnetserver#1]
Thanks for this amazing package! Great work! I'm using it on a Synology NAS, so one less computer to run!

I've spent some time till it finally worked, here are some information I'd like to share:

1. The user either needs to rename it's license file to `mayaserver.lic`, or needs to mount it via: 
```
-v path/mylicense.lic:/var/flexlm/mayaserver.lic
```
or specify `-c /var/flexlm/mylicense.lic` at the end. Figuring this out took me quite a while.

2. The user might prefer to have logging going into Docker logs. Then he needs to remove -l, which I  without the -l option.

**Comment by haysclark** [comment]
1) Very sorry about the magic value. I'll update the docs to explain what file name is expected.  I do not recall why I went with 'mayaserver.lic', maybe I should use ```/var/flexlm/adsk_server.lic``` because more than Maya used these license servers?  At the time I figured I was the only person that would actually use my container. 🙄 Originally I was expecting users to map a local 'flexlm' directory to the containers '/var/flexlm' directory. Like so:  ```-v /local-var/flexlm:/var/flexlm```.  As you mentioned, they would need to rename their license in the local 'flexlm' directory to 'mayaserver.lic'.

2) Let me know more about your logging issues.  

Here is my TL;DR; version:
The container is wrapping the 'lmgrd' command, and the only thing I MUST do is append the ```-z``` flag or the container will fall asleep. If you don't supply any custom arguments to _docker run_ then this command is executed in the container:

```
lmgrd -z -l /var/log/flexlm/lmgrd.log -c /var/flexlm/mayaserver.lic
```

If you provide any additional arguments to _docker run_ container it will drop ALL the default arguments seen above and only use the 'ENTRYPOINT'. Thus this is the resulting call:

    lmgrd -z [YOUR_ARGUMENTS]

In the end, I went with the minimal number of arguments for the 'entrypoint' so that 'lmgrd' power users could still monkey with the settings without anything getting in the way.

**Comment by hyperknot** [comment]
I think the file mapping is great, especially because they don't need to rename the file. Just the maya name sounds a bit weird, renaming it to adsk_server.lic is great.

For logging, there are no issues, except I have to manually specify something to make sure that the `-l ...` is not added. So all I want is entry_point + `-c ...`, without `-l`.

At the end, this is the full line I'm using in production:

```
docker run --name flexlm --detach --restart=always \
    --mac-address="12:34:56:ab:cd:ef" \
    -h host_name \
    -v /source/path.lic:/var/flexlm/lic.lic:ro \
    -p 2080:2080 -p 27000-27009:27000-27009 \
    haysclark/adlmflexnetserver \
    -c /var/flexlm/lic.lic
```

**Comment by haysclark** [comment]
@hyperknot Checkout this pull request, see if you like it. https://github.com/haysclark/adlmflexnetserver/pull/3

**Comment by hyperknot** [comment]
@haysclark looks great. Maybe an additional example for using the Docker logging would help as well, but this thread is here for people to look it up.
